// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC-GqOl5RrhL7pm7iAWXKaTSF6XNHsBcw',
    appId: '1:842988213591:web:ec8c722952d4ca1aed1a12',
    messagingSenderId: '842988213591',
    projectId: 'notesappiguess',
    authDomain: 'notesappiguess.firebaseapp.com',
    storageBucket: 'notesappiguess.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Y6x9-N3MvR_EeoqDdO8O7QxGYixJbUs',
    appId: '1:842988213591:android:7d65d541619e4cf2ed1a12',
    messagingSenderId: '842988213591',
    projectId: 'notesappiguess',
    storageBucket: 'notesappiguess.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb3hx22SxmXlZwr8zpVgRQGPkOiC72c80',
    appId: '1:842988213591:ios:f07a44ba5ea411e2ed1a12',
    messagingSenderId: '842988213591',
    projectId: 'notesappiguess',
    storageBucket: 'notesappiguess.appspot.com',
    iosClientId: '842988213591-rr1v2mmgl01fsuvnopub2rgn1cr3k6sh.apps.googleusercontent.com',
    iosBundleId: 'in.firstapp.dartprj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb3hx22SxmXlZwr8zpVgRQGPkOiC72c80',
    appId: '1:842988213591:ios:7817ce8498185628ed1a12',
    messagingSenderId: '842988213591',
    projectId: 'notesappiguess',
    storageBucket: 'notesappiguess.appspot.com',
    iosClientId: '842988213591-sj40djeo71igk5j8ph3bs25l1ib585ul.apps.googleusercontent.com',
    iosBundleId: 'in.firstapp.dartprj.RunnerTests',
  );
}
